services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  CloudflareDnsBundle\Command\:
    resource: '../../Command/'
  CloudflareDnsBundle\Controller\:
    resource: '../../Controller/'
  CloudflareDnsBundle\EventListener\:
    resource: '../../EventListener/'
  CloudflareDnsBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  CloudflareDnsBundle\Repository\:
    resource: '../../Repository/'
  CloudflareDnsBundle\Service\:
    resource: '../../Service/'
